name: nfl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - black
  - flake8
  - ipywidgets
  - ipykernel
  - isort
  - matplotlib
  - numpy
  - optuna
  - pandas
  - pip
  - pre-commit
  - pyarrow
  - pylint
#  - pymc>=5
  - scikit-learn
  - shap
  - tqdm
  - xgboost
  - pip:
      - nflreadpy
