# NOTE:
# PyMC requires a separate environment
# conda create -c conda-forge -n pymc_env python=3.10 "pymc>=5"

name: nfl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - black
  - flake8
  - ipywidgets
  - ipykernel
  - isort
  - matplotlib
  - numpy
  - optuna
  - pandas
  - pip
  - pre-commit
  - pyarrow
  - pylint
  - scikit-learn
  - shap
  - tqdm
  - xgboost
  - pip:
      - nflreadpy