name: nfl
channels:
  - conda-forge
dependencies:
  - arviz
  - h5netcdf
  - ipykernel
  - numpy
  - pandas
  - pip
  - polars
  - pyarrow
  - pymc>=6
  - pytest
  - python
  - ruff
  - pip:
      - nflreadpy
